name: Generate Vitality Calendar

on:
  schedule:
    - cron: "0 5 * * *"  # Tous les jours à 5h UTC
  workflow_dispatch:      # Permet un lancement manuel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate calendar
        run: python generate_calendar.py

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if [ -f vitality.ics ]; then
            git add vitality.ics
          else
            echo "⚠ Fichier vitality.ics introuvable, rien à committer."
            exit 0
          fi
          if git diff --cached --quiet; then
            echo "ℹ Aucun changement détecté dans vitality.ics."
          else
            git commit -m "Mise à jour du calendrier"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
            echo "✅ Calendrier mis à jour et pushé."
          fi