name: Update Calendar

on:
  schedule:
    # Lance le workflow tous les jours à 12h UTC
    - cron: '0 12 * * *'
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Generate calendar
      run: |
        python generate_calendar.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Ajouter le fichier spécifié dans config.json
        CALENDAR_FILE=$(python -c "import json; config=json.load(open('config.json')); print(config['output_file'])")
        
        if [ -f "$CALENDAR_FILE" ]; then
          git add "$CALENDAR_FILE"
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update calendar $(date -u +'%Y-%m-%d')"
            git push
            echo "✅ Calendar $CALENDAR_FILE updated successfully"
          fi
        else
          echo "⚠️ Calendar file $CALENDAR_FILE not found"
          exit 1
        fi
